using Xunit.Abstractions;

namespace SivayaanHMS.UatTests;

/// <summary>
/// The morning view of the business — today's patients, queue and revenue, each figure one click
/// from the screen that explains it.
/// </summary>
public sealed class DashboardUatTests(UatFixture fixture, ITestOutputHelper output) : UatTestBase(fixture, output)
{
    [Fact]
    public Task The_morning_dashboard() => RunWorkflowAsync("Dashboard");
}

/// <summary>
/// The patient register every other module is recorded against: a new patient added through the
/// real form, then found again by phone number and by a lower-case fragment of their name.
/// </summary>
public sealed class PatientRegisterUatTests(UatFixture fixture, ITestOutputHelper output) : UatTestBase(fixture, output)
{
    [Fact]
    public Task Registering_a_patient_and_finding_them_again() => RunWorkflowAsync("PatientRegister");
}

/// <summary>
/// The front desk: a queue that already carries the seed data's booking, and a fresh walk-in
/// booked against a doctor and a time that shows up alongside it.
/// </summary>
public sealed class OpdQueueUatTests(UatFixture fixture, ITestOutputHelper output) : UatTestBase(fixture, output)
{
    [Fact]
    public Task Booking_a_walk_in_into_the_queue() => RunWorkflowAsync("OpdQueue");
}

/// <summary>
/// The starter medicine catalogue seeded automatically at registration, searchable at the
/// Medicines screen and reachable from the Pharmacy counter where a sale is actually billed.
/// </summary>
public sealed class MedicineCatalogueUatTests(UatFixture fixture, ITestOutputHelper output) : UatTestBase(fixture, output)
{
    [Fact]
    public Task The_starter_catalogue_is_real_and_searchable() => RunWorkflowAsync("MedicineCatalogue");
}

/// <summary>
/// What a clinic reads back at the end of the day, generated by the server from today's actual
/// rows rather than recomputed on the page.
/// </summary>
public sealed class ReportsUatTests(UatFixture fixture, ITestOutputHelper output) : UatTestBase(fixture, output)
{
    [Fact]
    public Task Todays_visit_appears_in_the_opd_register() => RunWorkflowAsync("Reports");
}

/// <summary>
/// The clinic's own catalogue — here, the standard vaccination schedule that arrives seeded the
/// moment Pediatrics is switched on.
/// </summary>
public sealed class MastersUatTests(UatFixture fixture, ITestOutputHelper output) : UatTestBase(fixture, output)
{
    [Fact]
    public Task The_seeded_vaccine_schedule_is_in_masters() => RunWorkflowAsync("Masters");
}

/// <summary>
/// Growing into the product: a module that starts switched off, absent from the nav, reachable
/// the moment Settings &gt; Features turns it on — with no reload needed.
/// </summary>
public sealed class ModuleToggleUatTests(UatFixture fixture, ITestOutputHelper output) : UatTestBase(fixture, output)
{
    [Fact]
    public Task Turning_on_a_module_from_settings() => RunWorkflowAsync("ModuleToggle");
}
