namespace SivayaanHMS.Automation.Workflows;

/// <summary>
/// What a clinic reads back at the end of the day. Reports are generated by the server from
/// today's actual rows, not recomputed on the page, so a visit booked earlier in this same run has
/// to already be reflected here.
/// </summary>
public sealed class ReportsWorkflow() : Workflow(
    key: "Reports",
    displayName: "Reading Back Today's Work",
    module: "Reports",
    businessPurpose: "Turn the day's visits, bills and collections into the statements a clinic actually needs — without anyone re-typing a single figure into a spreadsheet.")
{
    public override async Task RunAsync(WorkflowContext c)
    {
        await c.StepAsync(
            "Reports opens on the Day Book, already showing today.",
            async () =>
            {
                await c.NavigateAsync("Reports", "Reports");
                await c.ExpectVisibleAsync("Day Book");
            });

        await c.StepAsync(
            "Switching to the OPD Register lists every visit booked today by name — including the one just booked in this run.",
            async () =>
            {
                await c.Button("OPD Register").ClickAsync();
                await c.ExpectVisibleAsync(DemoData.PatientOneName);
            });
    }
}
