<#
.SYNOPSIS
    Writes db\full-schema.sql: one psql script that takes a blank PostgreSQL
    server to a ready database - role, database, privileges, every table,
    index and foreign key, and the migration-history row - with no .NET SDK
    needed on the machine that runs it.

.DESCRIPTION
    The schema half is EF Core's own idempotent migration script, regenerated
    here so the file can never drift from the migrations; the role/database
    half mirrors deploy\sql\01-create-database.sql. Run it as postgres:

        psql -U postgres -v app_user='healthone_app' -v app_password='...' -f db\full-schema.sql
        psql -U postgres -v db_name='sivayaanhms_dev' -v developer=1 -f db\full-schema.sql

    Re-run this generator after every `dotnet ef migrations add`.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$Repo     = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$DataProj = Join-Path $Repo 'backend\src\SivayaanHMS.Data'
$Out      = Join-Path $Repo 'db\full-schema.sql'
$Migrate  = Join-Path $Repo 'db\migrate.sql'

$env:MSBUILDDISABLENODEREUSE = '1'
& dotnet ef migrations script --idempotent --project $DataProj --startup-project $DataProj -o $Migrate
if ($LASTEXITCODE -ne 0) { throw 'dotnet ef migrations script failed.' }

# Strip the BOM dotnet ef writes; it would land mid-file below.
$schema = (Get-Content $Migrate -Raw).TrimStart([char]0xFEFF)

$header = @'
-- ============================================================================
--  SivayaanHMS - complete database script for PostgreSQL 16+
--
--  GENERATED by deploy\New-FullSchemaScript.ps1 - do not edit by hand; the
--  schema half is EF Core's own migration script and must stay identical to
--  backend\src\SivayaanHMS.Data\Migrations.
--
--  Takes a blank server to a ready database in one run, as the superuser:
--
--      psql -U postgres -v app_user='healthone_app' -v app_password='...' -f full-schema.sql
--
--  Variables, all optional:
--
--    app_user      the login the application signs in as.  default sivayaanhms
--    app_password  that role's password.                   default sivayaanhms-dev
--    db_name       the database it owns.                   default sivayaanhms
--    developer     set to anything to also grant CREATEDB, which the unit
--                  tests and the UAT suite need (each creates a throwaway
--                  database per run). A production role is not given it.
--
--  What it does, in order:
--    1. the role, with that password (CREATEDB only if developer is set)
--    2. the database, owned by it, UTF-8
--    3. every privilege on the database and on schema public, including for
--       tables a later migration adds - explicit grants, so the script is
--       also correct against a database that already existed
--    4. connects, SET ROLE to the application role so every table below is
--       owned by it rather than by postgres, then creates every table, index
--       and foreign key, and the __EFMigrationsHistory row recording it
--
--  Safe to re-run: existing role and database are kept, already-applied
--  migrations are skipped.
--
--  DML: there is deliberately none beyond the migration-history row. Every
--  reference row a clinic needs - its admin user, diagnostic tests, vaccine
--  schedule, lab analytes and reports, dental procedures, import profiles -
--  is seeded PER CLINIC by the API the moment that clinic registers
--  (TenantProvisioner, backend\src\SivayaanHMS.Data\*Seeder.cs). Start the
--  API against this database and register a clinic through the Register
--  screen; nothing is inserted by hand.
--
--  Identifiers are double-quoted throughout: EF Core keeps the model's
--  PascalCase names, and PostgreSQL folds anything unquoted to lower case -
--  so in psql it is  SELECT * FROM "Patients";  not  patients.
-- ============================================================================

\set ON_ERROR_STOP on

\if :{?app_user}
\else
    \set app_user 'sivayaanhms'
\endif

\if :{?app_password}
\else
    \set app_password 'sivayaanhms-dev'
\endif

\if :{?db_name}
\else
    \set db_name 'sivayaanhms'
\endif

\echo Role :app_user, database :db_name

-- ---------------------------------------------------------------- 1. role

SELECT format('CREATE ROLE %I LOGIN PASSWORD %L', :'app_user', :'app_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'app_user')
\gexec

SELECT format('ALTER ROLE %I WITH LOGIN PASSWORD %L', :'app_user', :'app_password')
\gexec

\if :{?developer}
    SELECT format('ALTER ROLE %I CREATEDB', :'app_user')
    \gexec
\endif

-- ------------------------------------------------------------ 2. database

SELECT format('CREATE DATABASE %I OWNER %I ENCODING ''UTF8'' TEMPLATE template0',
              :'db_name', :'app_user')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'db_name')
\gexec

SELECT format('ALTER DATABASE %I OWNER TO %I', :'db_name', :'app_user')
\gexec

SELECT format('GRANT ALL PRIVILEGES ON DATABASE %I TO %I', :'db_name', :'app_user')
\gexec

-- --------------------------------------------------------- 3. privileges

\connect :db_name

-- From PostgreSQL 15 on, schema public no longer grants CREATE to everyone,
-- so a role that is not its owner cannot create a table in it.
SELECT format('ALTER SCHEMA public OWNER TO %I', :'app_user')
\gexec

SELECT format('GRANT ALL ON SCHEMA public TO %I', :'app_user')
\gexec

SELECT format('GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO %I', :'app_user')
\gexec

SELECT format('GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO %I', :'app_user')
\gexec

SELECT format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO %I', :'app_user')
\gexec

SELECT format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO %I', :'app_user')
\gexec

-- ----------------------------------------------- 4. schema, as that role

SET ROLE :"app_user";

'@

$footer = @'

-- ------------------------------------------------------------ 5. check

RESET ROLE;
\echo
\echo Applied migrations:
SELECT "MigrationId" FROM "__EFMigrationsHistory" ORDER BY 1;
\echo Tables, and who owns them:
SELECT count(*) AS tables, tableowner FROM pg_tables WHERE schemaname = 'public' GROUP BY tableowner;
\echo Done. Point the API at this database (docs/POSTGRESQL_SETUP.md section 3) and register a clinic.
'@

# UTF-8 *without* a byte-order mark. Windows PowerShell 5.1's
# Set-Content -Encoding utf8 always writes one, and psql does not skip it: the
# three bytes are glued onto the first statement, which then fails with
# 'syntax error at or near "ï»¿"' before anything has run.
[System.IO.File]::WriteAllText(
    [System.IO.Path]::GetFullPath($Out),
    ($header + $schema + $footer),
    (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $Out ($([math]::Round((Get-Item $Out).Length / 1KB)) KB)"
