<#
.SYNOPSIS
    Writes db\full-schema.sql: one psql script that takes a blank PostgreSQL
    server to a ready database - role, database, every table, index and
    foreign key, and the migration-history row - for a teammate who wants
    the same schema locally without the .NET SDK.

.DESCRIPTION
    The schema half is EF Core's own idempotent migration script, regenerated
    here so the file can never drift from the migrations; the role/database
    half is deploy\sql\01-create-database.sql inlined. Run it as postgres:

        psql -U postgres -f db\full-schema.sql
        psql -U postgres -v app_password='something-else' -v developer=1 -f db\full-schema.sql

    Re-run this generator after every `dotnet ef migrations add`.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$Repo     = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$DataProj = Join-Path $Repo 'backend\src\SivayaanHMS.Data'
$Out      = Join-Path $Repo 'db\full-schema.sql'
$Migrate  = Join-Path $Repo 'db\migrate.sql'

$env:MSBUILDDISABLENODEREUSE = '1'
& dotnet ef migrations script --idempotent --project $DataProj --startup-project $DataProj -o $Migrate
if ($LASTEXITCODE -ne 0) { throw 'dotnet ef migrations script failed.' }

# Strip the BOM dotnet ef writes; it would land mid-file below.
$schema = (Get-Content $Migrate -Raw).TrimStart([char]0xFEFF)

$header = @'
-- ============================================================================
--  SivayaanHMS - complete database script for PostgreSQL 16+
--
--  GENERATED by deploy\New-FullSchemaScript.ps1 - do not edit by hand; the
--  schema half is EF Core's own migration script and must stay identical to
--  backend\src\SivayaanHMS.Data\Migrations.
--
--  Takes a blank server to a ready database in one run, as the superuser:
--
--      psql -U postgres -f db\full-schema.sql
--
--  What it does, in order:
--    1. role      sivayaanhms  (LOGIN; password below - override it with
--                               -v app_password='...'; add -v developer=1 to
--                               grant CREATEDB, which the test suites need)
--    2. database  sivayaanhms  (owned by that role, UTF-8)
--    3. connects to it and SET ROLE sivayaanhms, so every table below is
--       owned by the application role, not by postgres
--    4. every table, index and foreign key, plus the __EFMigrationsHistory
--       row that records the migration as applied
--
--  Safe to re-run: existing role/database are kept, already-applied
--  migrations are skipped.
--
--  DML: there is deliberately none beyond the migration-history row. Every
--  reference row a clinic needs - its admin user, diagnostic tests, vaccine
--  schedule, lab analytes and reports, dental procedures, import profiles -
--  is seeded PER CLINIC by the API the moment that clinic registers
--  (TenantProvisioner, backend\src\SivayaanHMS.Data\*Seeder.cs). Start the
--  API against this database and register a clinic through the Register
--  screen; nothing is inserted by hand.
--
--  Identifiers are double-quoted throughout: EF Core keeps the model's
--  PascalCase names, and PostgreSQL folds anything unquoted to lower case -
--  so in psql it is  SELECT * FROM "Patients";  not  patients.
-- ============================================================================

\set ON_ERROR_STOP on

\if :{?app_password}
\else
    \set app_password 'sivayaanhms-dev'
\endif

-- ---------------------------------------------------------------- 1. role

SELECT format('CREATE ROLE sivayaanhms LOGIN PASSWORD %L', :'app_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sivayaanhms')
\gexec

SELECT format('ALTER ROLE sivayaanhms WITH LOGIN PASSWORD %L', :'app_password')
\gexec

\if :{?developer}
    ALTER ROLE sivayaanhms CREATEDB;
\endif

-- ------------------------------------------------------------ 2. database

SELECT 'CREATE DATABASE sivayaanhms OWNER sivayaanhms ENCODING ''UTF8'' TEMPLATE template0'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'sivayaanhms')
\gexec

-- ---------------------------------------------- 3. connect, as the owner

\connect sivayaanhms
SET ROLE sivayaanhms;

-- ------------------------------------------------- 4. schema (EF Core)

'@

$footer = @'

-- ------------------------------------------------------------ 5. check

RESET ROLE;
\echo
\echo Applied migrations:
SELECT "MigrationId" FROM "__EFMigrationsHistory" ORDER BY 1;
\echo Tables owned by sivayaanhms:
SELECT count(*) AS tables FROM pg_tables WHERE schemaname = 'public' AND tableowner = 'sivayaanhms';
\echo Done. Point the API at this database (docs/POSTGRESQL_SETUP.md section 3) and register a clinic.
'@

Set-Content -Path $Out -Value ($header + $schema + $footer) -Encoding utf8 -NoNewline
Write-Host "Wrote $Out ($([math]::Round((Get-Item $Out).Length / 1KB)) KB)"
