-- ============================================================================
--  SivayaanHMS - complete database script for PostgreSQL 16+
--
--  GENERATED by deploy\New-FullSchemaScript.ps1 - do not edit by hand; the
--  schema half is EF Core's own migration script and must stay identical to
--  backend\src\SivayaanHMS.Data\Migrations.
--
--  Takes a blank server to a ready database in one run, as the superuser:
--
--      psql -U postgres -f db\full-schema.sql
--
--  What it does, in order:
--    1. role      sivayaanhms  (LOGIN; password below - override it with
--                               -v app_password='...'; add -v developer=1 to
--                               grant CREATEDB, which the test suites need)
--    2. database  sivayaanhms  (owned by that role, UTF-8)
--    3. connects to it and SET ROLE sivayaanhms, so every table below is
--       owned by the application role, not by postgres
--    4. every table, index and foreign key, plus the __EFMigrationsHistory
--       row that records the migration as applied
--
--  Safe to re-run: existing role/database are kept, already-applied
--  migrations are skipped.
--
--  DML: there is deliberately none beyond the migration-history row. Every
--  reference row a clinic needs - its admin user, diagnostic tests, vaccine
--  schedule, lab analytes and reports, dental procedures, import profiles -
--  is seeded PER CLINIC by the API the moment that clinic registers
--  (TenantProvisioner, backend\src\SivayaanHMS.Data\*Seeder.cs). Start the
--  API against this database and register a clinic through the Register
--  screen; nothing is inserted by hand.
--
--  Identifiers are double-quoted throughout: EF Core keeps the model's
--  PascalCase names, and PostgreSQL folds anything unquoted to lower case -
--  so in psql it is  SELECT * FROM "Patients";  not  patients.
-- ============================================================================

\set ON_ERROR_STOP on

\if :{?app_password}
\else
    \set app_password 'sivayaanhms-dev'
\endif

-- ---------------------------------------------------------------- 1. role

SELECT format('CREATE ROLE sivayaanhms LOGIN PASSWORD %L', :'app_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sivayaanhms')
\gexec

SELECT format('ALTER ROLE sivayaanhms WITH LOGIN PASSWORD %L', :'app_password')
\gexec

\if :{?developer}
    ALTER ROLE sivayaanhms CREATEDB;
\endif

-- ------------------------------------------------------------ 2. database

SELECT 'CREATE DATABASE sivayaanhms OWNER sivayaanhms ENCODING ''UTF8'' TEMPLATE template0'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'sivayaanhms')
\gexec

-- ---------------------------------------------- 3. connect, as the owner

\connect sivayaanhms
SET ROLE sivayaanhms;

-- ------------------------------------------------- 4. schema (EF Core)
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "AnesthesiaTypeMasters" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "DefaultCost" numeric(12,2) NOT NULL,
        "Active" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_AnesthesiaTypeMasters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Counters" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Prefix" text NOT NULL,
        "LastNumber" integer NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Counters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "DentalPackageMasters" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "PackagePrice" numeric(12,2) NOT NULL,
        "Active" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_DentalPackageMasters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "DentalReplacementMasters" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Category" text NOT NULL,
        "UnitCost" numeric(12,2) NOT NULL,
        "Active" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_DentalReplacementMasters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "DiagnosticTests" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Category" text NOT NULL,
        "Price" numeric(12,2) NOT NULL,
        "Active" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_DiagnosticTests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Doctors" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "RegistrationNo" text,
        "Speciality" text,
        "Phone" text,
        "ConsultationFee" numeric(12,2) NOT NULL,
        "IsActive" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "H1Register" (
        "Id" uuid NOT NULL,
        "SoldOn" timestamp without time zone NOT NULL,
        "BillNo" text NOT NULL,
        "ProductName" text NOT NULL,
        "BatchNo" text NOT NULL,
        "Quantity" integer NOT NULL,
        "PatientName" text NOT NULL,
        "DoctorName" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_H1Register" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "ImportProfiles" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "ColumnMap" text NOT NULL,
        "DateFormats" text NOT NULL,
        "ExpiryFormats" text NOT NULL,
        "DefaultGstRate" numeric(12,2) NOT NULL,
        "IsActive" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_ImportProfiles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "LabAnalytes" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Category" text NOT NULL,
        "Units" text NOT NULL,
        "ResultType" integer NOT NULL,
        "DecimalPlaces" integer NOT NULL,
        "SequenceOrder" integer NOT NULL,
        "Active" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_LabAnalytes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "LabPackageMasters" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "PackagePrice" numeric(12,2) NOT NULL,
        "Active" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_LabPackageMasters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "LabReports" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Category" text NOT NULL,
        "Price" numeric(12,2) NOT NULL,
        "SequenceOrder" integer NOT NULL,
        "Active" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_LabReports" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Patients" (
        "Id" uuid NOT NULL,
        "PatientNo" text NOT NULL,
        "Name" text NOT NULL,
        "Phone" text NOT NULL,
        "Gender" integer NOT NULL,
        "Age" integer NOT NULL,
        "DateOfBirth" timestamp without time zone,
        "BloodGroup" text,
        "GuardianName" text,
        "Address" text,
        "Allergies" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Procedures" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Category" text NOT NULL,
        "Department" integer NOT NULL,
        "Price" numeric(12,2) NOT NULL,
        "Active" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Procedures" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Products" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "GenericName" text,
        "Manufacturer" text,
        "Composition" text,
        "Storage" text,
        "Strength" text,
        "StrengthValue" numeric(12,2),
        "PackSize" text,
        "DispensingUnit" integer NOT NULL,
        "UnitsPerPack" integer NOT NULL,
        "AllowLooseSale" boolean NOT NULL,
        "HsnCode" text NOT NULL,
        "GstRate" numeric(12,2) NOT NULL,
        "Schedule" integer NOT NULL,
        "RackLocation" text,
        "ReorderLevel" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "SearchKey" text NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Settings" (
        "Id" uuid NOT NULL,
        "Key" text NOT NULL,
        "Value" text NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Settings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "StockEntries" (
        "Id" uuid NOT NULL,
        "EntryNo" text NOT NULL,
        "EntryDate" timestamp without time zone NOT NULL,
        "SupplierName" text,
        "SupplierInvoiceNo" text,
        "TotalAmount" numeric(12,2) NOT NULL,
        "Notes" text,
        "ImportedFile" text,
        "ImportProfile" text,
        "NetAmount" numeric(12,2) NOT NULL,
        "DiscountPercent" numeric(12,2) NOT NULL,
        "IsProvisional" boolean NOT NULL,
        "EnteredBy" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_StockEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Tenants" (
        "Id" uuid NOT NULL,
        "Slug" text NOT NULL,
        "ClinicName" text NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        "LicenseExpiresOn" timestamp without time zone,
        CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "Username" text NOT NULL,
        "DisplayName" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "PasswordSalt" text NOT NULL,
        "Role" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "MustChangePassword" boolean NOT NULL,
        "LastLoginOn" timestamp without time zone,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "VaccineMasters" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "DoseNumber" integer NOT NULL,
        "RecommendedAgeDays" integer NOT NULL,
        "Category" text NOT NULL,
        "SequenceOrder" integer NOT NULL,
        "Active" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_VaccineMasters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "LabAnalyteReferenceRanges" (
        "Id" uuid NOT NULL,
        "AnalyteId" uuid NOT NULL,
        "Gender" integer,
        "MinAgeYears" numeric(12,2),
        "MaxAgeYears" numeric(12,2),
        "LowValue" numeric(12,2),
        "HighValue" numeric(12,2),
        "TextRange" text,
        "Label" text NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_LabAnalyteReferenceRanges" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LabAnalyteReferenceRanges_LabAnalytes_AnalyteId" FOREIGN KEY ("AnalyteId") REFERENCES "LabAnalytes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "LabPackageReports" (
        "Id" uuid NOT NULL,
        "PackageId" uuid NOT NULL,
        "ReportId" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_LabPackageReports" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LabPackageReports_LabPackageMasters_PackageId" FOREIGN KEY ("PackageId") REFERENCES "LabPackageMasters" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LabPackageReports_LabReports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "LabReports" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "LabReportAnalytes" (
        "Id" uuid NOT NULL,
        "ReportId" uuid NOT NULL,
        "AnalyteId" uuid NOT NULL,
        "SequenceOrder" integer NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_LabReportAnalytes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LabReportAnalytes_LabAnalytes_AnalyteId" FOREIGN KEY ("AnalyteId") REFERENCES "LabAnalytes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LabReportAnalytes_LabReports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "LabReports" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Appointments" (
        "Id" uuid NOT NULL,
        "AppointmentNo" text NOT NULL,
        "PatientId" uuid NOT NULL,
        "PatientName" text NOT NULL,
        "PatientPhone" text NOT NULL,
        "DoctorId" uuid NOT NULL,
        "DoctorName" text NOT NULL,
        "ScheduledOn" timestamp without time zone NOT NULL,
        "DurationMinutes" integer NOT NULL,
        "ModuleContext" integer NOT NULL,
        "Status" integer NOT NULL,
        "Reason" text,
        "Notes" text,
        "RescheduledFromId" uuid,
        "LinkedRecordId" uuid,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Appointments_Appointments_RescheduledFromId" FOREIGN KEY ("RescheduledFromId") REFERENCES "Appointments" ("Id"),
        CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "PediatricProfiles" (
        "Id" uuid NOT NULL,
        "PatientId" uuid NOT NULL,
        "FatherName" text,
        "MotherName" text,
        "ParentPhone" text,
        "ParentOccupation" text,
        "BirthWeightKg" numeric(12,2),
        "Notes" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_PediatricProfiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PediatricProfiles_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "ReminderLogs" (
        "Id" uuid NOT NULL,
        "SourceKind" integer NOT NULL,
        "SourceId" uuid NOT NULL,
        "PatientId" uuid NOT NULL,
        "DueOn" timestamp without time zone NOT NULL,
        "Channel" integer NOT NULL,
        "ActionedOn" timestamp without time zone,
        "ActionedBy" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_ReminderLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ReminderLogs_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "DentalCases" (
        "Id" uuid NOT NULL,
        "PatientId" uuid NOT NULL,
        "PatientName" text NOT NULL,
        "ProcedureId" uuid,
        "ProcedureName" text,
        "PackageId" uuid,
        "PackageName" text,
        "ToothNumber" text,
        "DoctorId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "StartedOn" timestamp without time zone NOT NULL,
        "CompletedOn" timestamp without time zone,
        "Notes" text,
        "BaseCost" numeric(12,2) NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_DentalCases" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DentalCases_DentalPackageMasters_PackageId" FOREIGN KEY ("PackageId") REFERENCES "DentalPackageMasters" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_DentalCases_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_DentalCases_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_DentalCases_Procedures_ProcedureId" FOREIGN KEY ("ProcedureId") REFERENCES "Procedures" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "DentalPackageItems" (
        "Id" uuid NOT NULL,
        "PackageId" uuid NOT NULL,
        "ProcedureId" uuid,
        "ProcedureName" text NOT NULL,
        "Quantity" integer NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_DentalPackageItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DentalPackageItems_DentalPackageMasters_PackageId" FOREIGN KEY ("PackageId") REFERENCES "DentalPackageMasters" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DentalPackageItems_Procedures_ProcedureId" FOREIGN KEY ("ProcedureId") REFERENCES "Procedures" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Batches" (
        "Id" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "BatchNo" text NOT NULL,
        "ExpiryDate" timestamp without time zone NOT NULL,
        "Mrp" numeric(12,2) NOT NULL,
        "PurchaseRate" numeric(12,2) NOT NULL,
        "QtyOnHand" integer NOT NULL,
        "UnitsPerPack" integer NOT NULL,
        "SupplierName" text,
        "SupplierInvoiceNo" text,
        "FreePacks" integer NOT NULL,
        "PacksReceived" integer NOT NULL,
        "ReceivedOn" timestamp without time zone NOT NULL,
        "IsProvisional" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Batches" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Batches_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "VendorProductCodes" (
        "Id" uuid NOT NULL,
        "VendorProfile" text NOT NULL,
        "Code" text NOT NULL,
        "ProductId" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_VendorProductCodes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VendorProductCodes_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "StockEntryItems" (
        "Id" uuid NOT NULL,
        "StockEntryId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "BatchNo" text NOT NULL,
        "ExpiryDate" timestamp without time zone NOT NULL,
        "Quantity" integer NOT NULL,
        "FreeQuantity" integer NOT NULL,
        "UnitsPerPack" integer NOT NULL,
        "PurchaseRate" numeric(12,2) NOT NULL,
        "Mrp" numeric(12,2) NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_StockEntryItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StockEntryItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_StockEntryItems_StockEntries_StockEntryId" FOREIGN KEY ("StockEntryId") REFERENCES "StockEntries" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Visits" (
        "Id" uuid NOT NULL,
        "VisitNo" text NOT NULL,
        "TokenNo" integer NOT NULL,
        "ScheduledOn" timestamp without time zone NOT NULL,
        "Status" integer NOT NULL,
        "PatientId" uuid NOT NULL,
        "DoctorId" uuid NOT NULL,
        "Complaint" text,
        "Diagnosis" text,
        "Notes" text,
        "WeightKg" numeric(12,2),
        "BloodPressure" text,
        "TemperatureF" numeric(12,2),
        "HeightCm" numeric(12,2),
        "HeartRateBpm" integer,
        "Spo2Percent" integer,
        "Fee" numeric(12,2) NOT NULL,
        "FeePaid" boolean NOT NULL,
        "FeeReceiptNo" text,
        "FeePaidOn" timestamp without time zone,
        "FeePaymentMode" integer,
        "FeeTransactionNo" text,
        "FollowUpOn" timestamp without time zone,
        "AppointmentId" uuid,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Visits" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Visits_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Visits_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Visits_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "DentalCaseReplacements" (
        "Id" uuid NOT NULL,
        "DentalCaseId" uuid NOT NULL,
        "ReplacementId" uuid,
        "Name" text NOT NULL,
        "UnitCost" numeric(12,2) NOT NULL,
        "Quantity" integer NOT NULL,
        "Amount" numeric(12,2) NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_DentalCaseReplacements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DentalCaseReplacements_DentalCases_DentalCaseId" FOREIGN KEY ("DentalCaseId") REFERENCES "DentalCases" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DentalCaseReplacements_DentalReplacementMasters_Replacement~" FOREIGN KEY ("ReplacementId") REFERENCES "DentalReplacementMasters" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "DentalPayments" (
        "Id" uuid NOT NULL,
        "DentalCaseId" uuid NOT NULL,
        "ReceiptNo" text NOT NULL,
        "PaidOn" timestamp without time zone NOT NULL,
        "Amount" numeric(12,2) NOT NULL,
        "PaymentMode" integer NOT NULL,
        "TransactionNo" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_DentalPayments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DentalPayments_DentalCases_DentalCaseId" FOREIGN KEY ("DentalCaseId") REFERENCES "DentalCases" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "DentalSittings" (
        "Id" uuid NOT NULL,
        "DentalCaseId" uuid NOT NULL,
        "SittingNumber" integer NOT NULL,
        "SittingDate" timestamp without time zone NOT NULL,
        "DoctorId" uuid NOT NULL,
        "WorkDone" text,
        "AnesthesiaTypeId" uuid,
        "AnesthesiaTypeName" text,
        "AnesthesiaCost" numeric(12,2),
        "NextSittingOn" timestamp without time zone,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_DentalSittings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DentalSittings_AnesthesiaTypeMasters_AnesthesiaTypeId" FOREIGN KEY ("AnesthesiaTypeId") REFERENCES "AnesthesiaTypeMasters" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_DentalSittings_DentalCases_DentalCaseId" FOREIGN KEY ("DentalCaseId") REFERENCES "DentalCases" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DentalSittings_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "StockAdjustments" (
        "Id" uuid NOT NULL,
        "AdjustedOn" timestamp without time zone NOT NULL,
        "BatchId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "ProductName" text NOT NULL,
        "BatchNo" text NOT NULL,
        "QuantityBefore" integer NOT NULL,
        "QuantityAfter" integer NOT NULL,
        "Reason" integer NOT NULL,
        "Notes" text,
        "AdjustedBy" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_StockAdjustments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StockAdjustments_Batches_BatchId" FOREIGN KEY ("BatchId") REFERENCES "Batches" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_StockAdjustments_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "VaccinationRecords" (
        "Id" uuid NOT NULL,
        "PatientId" uuid NOT NULL,
        "PatientName" text NOT NULL,
        "VaccineId" uuid,
        "VaccineName" text NOT NULL,
        "DoseNumber" integer NOT NULL,
        "GivenOn" timestamp without time zone NOT NULL,
        "BatchNo" text,
        "SiteOfInjection" text,
        "AdministeredBy" text,
        "ProductId" uuid,
        "ProductName" text,
        "Manufacturer" text,
        "BatchId" uuid,
        "NextDueOn" timestamp without time zone,
        "ProcedureBillItemId" uuid,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_VaccinationRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VaccinationRecords_Batches_BatchId" FOREIGN KEY ("BatchId") REFERENCES "Batches" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_VaccinationRecords_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_VaccinationRecords_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_VaccinationRecords_VaccineMasters_VaccineId" FOREIGN KEY ("VaccineId") REFERENCES "VaccineMasters" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "DiagnosticBills" (
        "Id" uuid NOT NULL,
        "BillNo" text NOT NULL,
        "BillDate" timestamp without time zone NOT NULL,
        "PatientId" uuid NOT NULL,
        "PatientName" text NOT NULL,
        "PatientNo" text NOT NULL,
        "TotalAmount" numeric(12,2) NOT NULL,
        "Discount" numeric(12,2) NOT NULL,
        "FinalAmount" numeric(12,2) NOT NULL,
        "PaymentMode" integer NOT NULL,
        "TransactionNo" text,
        "Status" integer NOT NULL,
        "Remarks" text,
        "VisitId" uuid,
        "ReferredBy" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_DiagnosticBills" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DiagnosticBills_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_DiagnosticBills_Visits_VisitId" FOREIGN KEY ("VisitId") REFERENCES "Visits" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "GrowthMeasurements" (
        "Id" uuid NOT NULL,
        "PatientId" uuid NOT NULL,
        "VisitId" uuid,
        "MeasuredOn" timestamp without time zone NOT NULL,
        "AgeDays" integer NOT NULL,
        "WeightKg" numeric(12,2),
        "HeightCm" numeric(12,2),
        "HeadCircumferenceCm" numeric(12,2),
        "BmiValue" numeric(12,2),
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_GrowthMeasurements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GrowthMeasurements_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_GrowthMeasurements_Visits_VisitId" FOREIGN KEY ("VisitId") REFERENCES "Visits" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "LabOrders" (
        "Id" uuid NOT NULL,
        "OrderNo" text NOT NULL,
        "OrderDate" timestamp without time zone NOT NULL,
        "PatientId" uuid NOT NULL,
        "PatientName" text NOT NULL,
        "PatientNo" text NOT NULL,
        "PackageId" uuid,
        "VisitId" uuid,
        "ReferredBy" text,
        "SpecimenId" text,
        "CollectedOn" timestamp without time zone,
        "ReceivedOn" timestamp without time zone,
        "TotalAmount" numeric(12,2) NOT NULL,
        "Discount" numeric(12,2) NOT NULL,
        "FinalAmount" numeric(12,2) NOT NULL,
        "PaymentMode" integer NOT NULL,
        "TransactionNo" text,
        "Status" integer NOT NULL,
        "Remarks" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_LabOrders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LabOrders_LabPackageMasters_PackageId" FOREIGN KEY ("PackageId") REFERENCES "LabPackageMasters" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_LabOrders_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_LabOrders_Visits_VisitId" FOREIGN KEY ("VisitId") REFERENCES "Visits" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "PrescriptionItems" (
        "Id" uuid NOT NULL,
        "VisitId" uuid NOT NULL,
        "ProductId" uuid,
        "MedicineName" text NOT NULL,
        "Dosage" text,
        "Frequency" text,
        "Days" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "Instructions" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_PrescriptionItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PrescriptionItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id"),
        CONSTRAINT "FK_PrescriptionItems_Visits_VisitId" FOREIGN KEY ("VisitId") REFERENCES "Visits" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "ProcedureBills" (
        "Id" uuid NOT NULL,
        "BillNo" text NOT NULL,
        "BillDate" timestamp without time zone NOT NULL,
        "PatientId" uuid NOT NULL,
        "PatientName" text NOT NULL,
        "PatientNo" text NOT NULL,
        "TotalAmount" numeric(12,2) NOT NULL,
        "Discount" numeric(12,2) NOT NULL,
        "FinalAmount" numeric(12,2) NOT NULL,
        "PaymentMode" integer NOT NULL,
        "TransactionNo" text,
        "Status" integer NOT NULL,
        "VisitId" uuid,
        "ReferredBy" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_ProcedureBills" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProcedureBills_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ProcedureBills_Visits_VisitId" FOREIGN KEY ("VisitId") REFERENCES "Visits" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "Sales" (
        "Id" uuid NOT NULL,
        "BillNo" text NOT NULL,
        "BillDate" timestamp without time zone NOT NULL,
        "PatientId" uuid,
        "VisitId" uuid,
        "CustomerName" text NOT NULL,
        "DoctorName" text,
        "GrossAmount" numeric(12,2) NOT NULL,
        "DiscountAmount" numeric(12,2) NOT NULL,
        "TaxableAmount" numeric(12,2) NOT NULL,
        "CgstAmount" numeric(12,2) NOT NULL,
        "SgstAmount" numeric(12,2) NOT NULL,
        "RoundOff" numeric(12,2) NOT NULL,
        "NetAmount" numeric(12,2) NOT NULL,
        "PaymentMode" integer NOT NULL,
        "Status" integer NOT NULL,
        "TransactionNo" text,
        "IsTaxInvoice" boolean NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_Sales" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sales_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Sales_Visits_VisitId" FOREIGN KEY ("VisitId") REFERENCES "Visits" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "VisitDiagnosticRequests" (
        "Id" uuid NOT NULL,
        "VisitId" uuid NOT NULL,
        "TestId" uuid,
        "TestName" text NOT NULL,
        "Notes" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_VisitDiagnosticRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VisitDiagnosticRequests_DiagnosticTests_TestId" FOREIGN KEY ("TestId") REFERENCES "DiagnosticTests" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_VisitDiagnosticRequests_Visits_VisitId" FOREIGN KEY ("VisitId") REFERENCES "Visits" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "DiagnosticBillItems" (
        "Id" uuid NOT NULL,
        "BillId" uuid NOT NULL,
        "TestId" uuid,
        "TestName" text NOT NULL,
        "Price" numeric(12,2) NOT NULL,
        "Quantity" integer NOT NULL,
        "Amount" numeric(12,2) NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_DiagnosticBillItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DiagnosticBillItems_DiagnosticBills_BillId" FOREIGN KEY ("BillId") REFERENCES "DiagnosticBills" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DiagnosticBillItems_DiagnosticTests_TestId" FOREIGN KEY ("TestId") REFERENCES "DiagnosticTests" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "LabOrderReports" (
        "Id" uuid NOT NULL,
        "OrderId" uuid NOT NULL,
        "ReportId" uuid,
        "ReportName" text NOT NULL,
        "Price" numeric(12,2) NOT NULL,
        "Amount" numeric(12,2) NOT NULL,
        "Notes" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_LabOrderReports" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LabOrderReports_LabOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "LabOrders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LabOrderReports_LabReports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "LabReports" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "ProcedureBillItems" (
        "Id" uuid NOT NULL,
        "BillId" uuid NOT NULL,
        "ProcedureId" uuid,
        "ProcedureName" text NOT NULL,
        "Price" numeric(12,2) NOT NULL,
        "Quantity" integer NOT NULL,
        "Amount" numeric(12,2) NOT NULL,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_ProcedureBillItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProcedureBillItems_ProcedureBills_BillId" FOREIGN KEY ("BillId") REFERENCES "ProcedureBills" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProcedureBillItems_Procedures_ProcedureId" FOREIGN KEY ("ProcedureId") REFERENCES "Procedures" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "SaleItems" (
        "Id" uuid NOT NULL,
        "SaleId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "BatchId" uuid NOT NULL,
        "ProductName" text NOT NULL,
        "BatchNo" text NOT NULL,
        "ExpiryDate" timestamp without time zone NOT NULL,
        "HsnCode" text NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitsPerPack" integer NOT NULL,
        "Mrp" numeric(12,2) NOT NULL,
        "DiscountPercent" numeric(12,2) NOT NULL,
        "GstRate" numeric(12,2) NOT NULL,
        "TaxableAmount" numeric(12,2) NOT NULL,
        "GstAmount" numeric(12,2) NOT NULL,
        "LineTotal" numeric(12,2) NOT NULL,
        "PackLabel" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_SaleItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SaleItems_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE TABLE "LabResults" (
        "Id" uuid NOT NULL,
        "OrderReportId" uuid NOT NULL,
        "AnalyteId" uuid,
        "AnalyteName" text NOT NULL,
        "Units" text NOT NULL,
        "ResultValue" text NOT NULL,
        "ReferenceRangeDisplay" text NOT NULL,
        "Flag" integer NOT NULL,
        "EnteredOn" timestamp without time zone NOT NULL,
        "EnteredBy" text,
        "VerifiedOn" timestamp without time zone,
        "VerifiedBy" text,
        "TenantId" uuid NOT NULL,
        "RowVersion" bytea NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        "IsDeleted" boolean NOT NULL,
        "CreatedByUserId" uuid,
        "UpdatedByUserId" uuid,
        CONSTRAINT "PK_LabResults" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LabResults_LabAnalytes_AnalyteId" FOREIGN KEY ("AnalyteId") REFERENCES "LabAnalytes" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_LabResults_LabOrderReports_OrderReportId" FOREIGN KEY ("OrderReportId") REFERENCES "LabOrderReports" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_AnesthesiaTypeMasters_Name" ON "AnesthesiaTypeMasters" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Appointments_DoctorId" ON "Appointments" ("DoctorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Appointments_PatientId" ON "Appointments" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Appointments_RescheduledFromId" ON "Appointments" ("RescheduledFromId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Appointments_ScheduledOn" ON "Appointments" ("ScheduledOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Appointments_TenantId_AppointmentNo" ON "Appointments" ("TenantId", "AppointmentNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Batches_ProductId_BatchNo" ON "Batches" ("ProductId", "BatchNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Counters_TenantId_Name" ON "Counters" ("TenantId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalCaseReplacements_DentalCaseId" ON "DentalCaseReplacements" ("DentalCaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalCaseReplacements_ReplacementId" ON "DentalCaseReplacements" ("ReplacementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalCases_DoctorId" ON "DentalCases" ("DoctorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalCases_PackageId" ON "DentalCases" ("PackageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalCases_PatientId" ON "DentalCases" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalCases_ProcedureId" ON "DentalCases" ("ProcedureId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalPackageItems_PackageId" ON "DentalPackageItems" ("PackageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalPackageItems_ProcedureId" ON "DentalPackageItems" ("ProcedureId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalPackageMasters_Name" ON "DentalPackageMasters" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalPayments_DentalCaseId" ON "DentalPayments" ("DentalCaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalPayments_PaidOn" ON "DentalPayments" ("PaidOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_DentalPayments_TenantId_ReceiptNo" ON "DentalPayments" ("TenantId", "ReceiptNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalReplacementMasters_Name" ON "DentalReplacementMasters" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalSittings_AnesthesiaTypeId" ON "DentalSittings" ("AnesthesiaTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalSittings_DentalCaseId" ON "DentalSittings" ("DentalCaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DentalSittings_DoctorId" ON "DentalSittings" ("DoctorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DiagnosticBillItems_BillId" ON "DiagnosticBillItems" ("BillId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DiagnosticBillItems_TestId" ON "DiagnosticBillItems" ("TestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DiagnosticBills_BillDate" ON "DiagnosticBills" ("BillDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DiagnosticBills_PatientId" ON "DiagnosticBills" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_DiagnosticBills_TenantId_BillNo" ON "DiagnosticBills" ("TenantId", "BillNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DiagnosticBills_VisitId" ON "DiagnosticBills" ("VisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_DiagnosticTests_Name" ON "DiagnosticTests" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_GrowthMeasurements_PatientId" ON "GrowthMeasurements" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_GrowthMeasurements_VisitId" ON "GrowthMeasurements" ("VisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ImportProfiles_TenantId_Name" ON "ImportProfiles" ("TenantId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabAnalyteReferenceRanges_AnalyteId" ON "LabAnalyteReferenceRanges" ("AnalyteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabAnalytes_Name" ON "LabAnalytes" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabOrderReports_OrderId" ON "LabOrderReports" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabOrderReports_ReportId" ON "LabOrderReports" ("ReportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabOrders_OrderDate" ON "LabOrders" ("OrderDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabOrders_PackageId" ON "LabOrders" ("PackageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabOrders_PatientId" ON "LabOrders" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_LabOrders_TenantId_OrderNo" ON "LabOrders" ("TenantId", "OrderNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabOrders_VisitId" ON "LabOrders" ("VisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabPackageMasters_Name" ON "LabPackageMasters" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabPackageReports_PackageId" ON "LabPackageReports" ("PackageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabPackageReports_ReportId" ON "LabPackageReports" ("ReportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabReportAnalytes_AnalyteId" ON "LabReportAnalytes" ("AnalyteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabReportAnalytes_ReportId" ON "LabReportAnalytes" ("ReportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabReports_Name" ON "LabReports" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabResults_AnalyteId" ON "LabResults" ("AnalyteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_LabResults_OrderReportId" ON "LabResults" ("OrderReportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Patients_Name" ON "Patients" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Patients_Phone" ON "Patients" ("Phone");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Patients_TenantId_PatientNo" ON "Patients" ("TenantId", "PatientNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PediatricProfiles_PatientId" ON "PediatricProfiles" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_PrescriptionItems_ProductId" ON "PrescriptionItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_PrescriptionItems_VisitId" ON "PrescriptionItems" ("VisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_ProcedureBillItems_BillId" ON "ProcedureBillItems" ("BillId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_ProcedureBillItems_ProcedureId" ON "ProcedureBillItems" ("ProcedureId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_ProcedureBills_BillDate" ON "ProcedureBills" ("BillDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_ProcedureBills_PatientId" ON "ProcedureBills" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ProcedureBills_TenantId_BillNo" ON "ProcedureBills" ("TenantId", "BillNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_ProcedureBills_VisitId" ON "ProcedureBills" ("VisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Procedures_Department_Name" ON "Procedures" ("Department", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Products_Name" ON "Products" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Products_TenantId_SearchKey" ON "Products" ("TenantId", "SearchKey") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_ReminderLogs_DueOn" ON "ReminderLogs" ("DueOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_ReminderLogs_PatientId" ON "ReminderLogs" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_SaleItems_SaleId" ON "SaleItems" ("SaleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Sales_BillDate" ON "Sales" ("BillDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Sales_PatientId" ON "Sales" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Sales_TenantId_BillNo" ON "Sales" ("TenantId", "BillNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Sales_VisitId" ON "Sales" ("VisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Settings_TenantId_Key" ON "Settings" ("TenantId", "Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_StockAdjustments_AdjustedOn" ON "StockAdjustments" ("AdjustedOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_StockAdjustments_BatchId" ON "StockAdjustments" ("BatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_StockAdjustments_ProductId" ON "StockAdjustments" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_StockEntries_SupplierInvoiceNo" ON "StockEntries" ("SupplierInvoiceNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_StockEntries_TenantId_EntryNo" ON "StockEntries" ("TenantId", "EntryNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_StockEntryItems_ProductId" ON "StockEntryItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_StockEntryItems_StockEntryId" ON "StockEntryItems" ("StockEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Tenants_Slug" ON "Tenants" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_VaccinationRecords_BatchId" ON "VaccinationRecords" ("BatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_VaccinationRecords_PatientId" ON "VaccinationRecords" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_VaccinationRecords_ProductId" ON "VaccinationRecords" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_VaccinationRecords_VaccineId" ON "VaccinationRecords" ("VaccineId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_VaccineMasters_Name" ON "VaccineMasters" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_VendorProductCodes_ProductId" ON "VendorProductCodes" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_VendorProductCodes_TenantId_VendorProfile_Code" ON "VendorProductCodes" ("TenantId", "VendorProfile", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_VisitDiagnosticRequests_TestId" ON "VisitDiagnosticRequests" ("TestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_VisitDiagnosticRequests_VisitId" ON "VisitDiagnosticRequests" ("VisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Visits_AppointmentId" ON "Visits" ("AppointmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Visits_DoctorId" ON "Visits" ("DoctorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Visits_FeePaidOn" ON "Visits" ("FeePaidOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Visits_FollowUpOn" ON "Visits" ("FollowUpOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Visits_PatientId" ON "Visits" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE INDEX "IX_Visits_ScheduledOn" ON "Visits" ("ScheduledOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Visits_TenantId_VisitNo" ON "Visits" ("TenantId", "VisitNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920032241_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260920032241_InitialCreate', '10.0.11');
    END IF;
END $EF$;
COMMIT;


-- ------------------------------------------------------------ 5. check

RESET ROLE;
\echo
\echo Applied migrations:
SELECT "MigrationId" FROM "__EFMigrationsHistory" ORDER BY 1;
\echo Tables owned by sivayaanhms:
SELECT count(*) AS tables FROM pg_tables WHERE schemaname = 'public' AND tableowner = 'sivayaanhms';
\echo Done. Point the API at this database (docs/POSTGRESQL_SETUP.md section 3) and register a clinic.